import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="antialiased flex flex-col h-screen">
        <header className="w-full h-16 bg-neutral-200 flex items-center justify-center">
          <p className="text-xl text-neutral-700 font-bold uppercase">header</p>
        </header>

        <div className="flex-1 flex">{children}</div>

        <footer className="w-full h-16 bg-neutral-200 flex items-center justify-center">
          <p className="text-xl text-neutral-700 font-bold uppercase">footer</p>
        </footer>
      </body>
    </html>
  );
}
